const instruments = {
  piano: {
    name: 'piano',
    key: 'c',
    transposeFactor: 0,
    icon: true,
    iconName: 'piano',
  },
  'alto-clarinet': {
    name: 'alto clarinet',
    key: 'e-flat',
    transposeFactor: 3,
    icon: false,
    iconName: 'alto-clarinet',
  },
  'alto-sax': {
    name: 'alto sax',
    key: 'e-flat',
    transposeFactor: 3,
    icon: true,
    iconName: 'alto-sax',
  },
  'bari-sax': {
    name: 'baritone sax',
    key: 'e-flat',
    transposeFactor: 3,
    icon: true,
    iconName: 'bari-sax',
  },
  'baritone-horn': {
    name: 'baritone horn',
    key: 'b-flat',
    transposeFactor: 2,
    icon: true,
    iconName: 'baritone-horn',
  },
  'bass-clarinet': {
    name: 'bass clarinet',
    key: 'b-flat',
    transposeFactor: 2,
    icon: false,
    iconName: 'bass-clarinet',
  },
  cello: {
    name: 'cello',
    key: 'c',
    transposeFactor: 0,
    icon: true,
    iconName: 'cello',
  },
  clarinet: {
    name: 'clarinet',
    key: 'b-flat',
    transposeFactor: 2,
    icon: true,
    iconName: 'clarinet',
  },
  'double-bass': {
    name: 'double bass',
    key: 'c',
    transposeFactor: 0,
    icon: true,
    iconName: 'double-bass',
  },
  flute: {
    name: 'flute',
    key: 'c',
    transposeFactor: 0,
    icon: true,
    iconName: 'flute',
  },
  guitar: {
    name: 'guitar',
    key: 'c',
    transposeFactor: 0,
    icon: true,
    iconName: 'guitar',
  },
  'french-horn': {
    name: 'french horn',
    key: 'f',
    transposeFactor: 1,
    icon: true,
    iconName: 'french-horn',
  },
  oboe: {
    name: 'oboe',
    key: 'c',
    transposeFactor: 0,
    icon: false,
    iconName: 'oboe',
  },
  'soprano-sax': {
    name: 'soprano sax',
    key: 'b-flat',
    transposeFactor: 2,
    icon: true,
    iconName: 'soprano-sax',
  },
  'tenor-sax': {
    name: 'tenor sax',
    key: 'b-flat',
    transposeFactor: 2,
    icon: true,
    iconName: 'tenor-sax',
  },
  trombone: {
    name: 'trombone',
    key: 'c',
    transposeFactor: 0,
    icon: true,
    iconName: 'trombone',
  },
  trumpet: {
    name: 'trumpet',
    key: 'b-flat',
    transposeFactor: 2,
    icon: true,
    iconName: 'trumpet',
  },
  tuba: {
    name: 'tuba',
    key: 'c',
    transposeFactor: 0,
    icon: true,
    iconName: 'tuba',
  },
  viola: {
    name: 'viola',
    key: 'c',
    transposeFactor: 0,
    icon: true,
    iconName: 'viola',
  },
  violin: {
    name: 'violin',
    key: 'c',
    transposeFactor: 0,
    icon: true,
    iconName: 'violin',
  },
};

export default instruments;
