const scaleKeys = {
  c: {
    major: 'natural',
    minor: 'flat',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'flat',
    phyrygian: 'flat',
    lydian: 'sharp',
    mixolydian: 'flat',
    locrian: 'flat',
  },
  g: {
    major: 'sharp',
    minor: 'flat',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'flat',
    phyrygian: 'flat',
    lydian: 'sharp',
    mixolydian: 'natural',
    locrian: 'flat',
  },
  d: {
    major: 'sharp',
    minor: 'flat',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'natural',
    phyrygian: 'flat',
    lydian: 'sharp',
    mixolydian: 'sharp',
    locrian: 'flat',
  },
  a: {
    major: 'sharp',
    minor: 'natural',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'sharp',
    phyrygian: 'natural',
    lydian: 'sharp',
    mixolydian: 'sharp',
    locrian: 'flat',
  },
  e: {
    major: 'sharp',
    minor: 'sharp',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'sharp',
    phyrygian: 'natural',
    lydian: 'sharp',
    mixolydian: 'sharp',
    locrian: 'flat',
  },
  b: {
    major: 'sharp',
    minor: 'sharp',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'sharp',
    phyrygian: 'sharp',
    lydian: 'sharp',
    mixolydian: 'sharp',
    locrian: 'natrual',
  },
  gFlat: {
    major: 'sharp',
    minor: 'sharp',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'sharp',
    phyrygian: 'sharp',
    lydian: 'flat',
    mixolydian: 'sharp',
    locrian: 'sharp',
  },
  dFlat: {
    major: 'flat',
    minor: 'sharp',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'sharp',
    phyrygian: 'sharp',
    lydian: 'flat',
    mixolydian: 'sharp',
    locrian: 'sharp',
  },
  aFlat: {
    major: 'sharp',
    minor: 'sharp',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'sharp',
    phyrygian: 'sharp',
    lydian: 'flat',
    mixolydian: 'flat',
    locrian: 'sharp',
  },
  eFlat: {
    major: 'flat',
    minor: 'sharp',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'flat',
    phyrygian: 'sharp',
    lydian: 'flat',
    mixolydian: 'flat',
    locrian: 'sharp',
  },
  bFlat: {
    major: 'flat',
    minor: 'flat',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'flat',
    phyrygian: 'sharp',
    lydian: 'flat',
    mixolydian: 'flat',
    locrian: 'sharp',
  },
  f: {
    major: 'flat',
    minor: 'flat',
    majorPentatonic: 'flat',
    minorPentatonic: 'flat',
    bluesMinor: 'flat',
    bluesMajor: 'flat',
    dorian: 'flat',
    phyrygian: 'flat',
    lydian: 'natural',
    mixolydian: 'flat',
    locrian: 'flat',
  },
};

export default scaleKeys;
