<template>
  <div class="circle-menu">
    <!-- SVG Menu Generated By CIRCULUS.SVG :: http://sarasoueidan.com/tools/circulus -->
    <h2 v-html="transposedNote.display"></h2>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      viewBox="-2 -2 504 504"
      id="menu"
      style="transform-origin: 50% 50% 0px; transform: translate3d(0px, 0px, 0px); touch-action: none; -webkit-user-select: none;"
    >
      <g id="symbolsContainer" class="notes-container">
        <symbol class="note" id="icon-1" viewBox="0 0 40 40">
          <text x="50%" y="50%" dy=".5em" text-anchor="middle">C</text>
        </symbol>
        <symbol class="note" id="icon-2" viewBox="0 0 40 40">
          <text x="50%" y="50%" dy=".5em" text-anchor="middle">G</text>
        </symbol>
        <symbol class="note" id="icon-3" viewBox="0 0 40 40">
          <text x="50%" y="50%" dy=".5em" text-anchor="middle">D</text>
        </symbol>
        <symbol class="note" id="icon-4" viewBox="0 0 40 40">
          <text x="50%" y="50%" dy=".5em" text-anchor="middle">A</text>
        </symbol>
        <symbol class="note" id="icon-5" viewBox="0 0 40 40">
          <text x="50%" y="50%" dy=".5em" text-anchor="middle">E</text>
        </symbol>
        <symbol class="note" id="icon-6" viewBox="0 0 40 40">
          <text x="50%" y="50%" dy=".5em" text-anchor="middle">B</text>
        </symbol>
        <symbol class="note with-enharmonic" id="icon-7" viewBox="0 0 40 40">
          <text x="15%" y="0" dy=".5em">F</text>
          <text x="60%" y="25%" class="sharp">&#X266F;</text>
          <text x="10%" y="80%" dy=".5em" class="enharmonic">G</text>
          <text x="55%" y="105%" class="enharmonic flat">&#X266D;</text>
        </symbol>
        <symbol class="note with-enharmonic" id="icon-8" viewBox="0 0 40 40">
          <text x="15%" y="0" dy=".5em">D</text>
          <text x="65%" y="25%" class="flat">&#X266D;</text>
          <text x="10%" y="80%" dy=".5em" class="enharmonic">C</text>
          <text x="55%" y="105%" class="enharmonic sharp">&#X266F;</text>
        </symbol>
        <symbol class="note with-enharmonic" id="icon-9" viewBox="0 0 40 40">
          <text x="15%" y="0" dy=".5em">A</text>
          <text x="60%" y="25%" class="flat">&#X266D;</text>
          <text x="10%" y="80%" dy=".5em" class="enharmonic">G</text>
          <text x="55%" y="105%" class="enharmonic sharp">&#X266F;</text>
        </symbol>
        <symbol class="note with-enharmonic" id="icon-10" viewBox="0 0 40 40">
          <text x="15%" y="0" dy=".5em">E</text>
          <text x="60%" y="25%" class="flat">&#X266D;</text>
          <text x="10%" y="80%" dy=".5em" class="enharmonic">D</text>
          <text x="55%" y="105%" class="enharmonic sharp">&#X266F;</text>
        </symbol>
        <symbol class="note with-enharmonic" id="icon-11" viewBox="0 0 40 40">
          <text x="15%" y="0" dy=".5em">B</text>
          <text x="60%" y="25%" class="flat">&#X266D;</text>
          <text x="10%" y="80%" dy=".5em" class="enharmonic">A</text>
          <text x="55%" y="105%" class="enharmonic sharp">&#X266F;</text>
        </symbol>
        <symbol class="note" id="icon-12" viewBox="0 0 40 40">
          <text x="50%" y="50%" dy=".5em" text-anchor="middle">F</text>
        </symbol>
        <symbol class="indicator" id="indicator" viewBox="0 0 40 40">
          <polygon
            transform="translate(20.000000, 20.000000) scale(1, -1) translate(-20.000000, -20.000000) "
            points="40 0 40 40 0 40 "
          ></polygon>
        </symbol>
      </g>
      <g id="itemsContainer">
        <a
          class="item"
          ref="note1"
          tabindex="0"
          transform="matrix(0,-1,1,0,0,500)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(1)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--C-->
          <use
            xlink:href="#icon-1"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(90 415 210)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note2"
          tabindex="0"
          transform="matrix(0.5,-0.86602,0.86602,0.5,-91.5063509461097,341.5063509461096)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(2)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--G-->
          <use
            xlink:href="#icon-2"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(60 415 210)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note3"
          tabindex="0"
          transform="matrix(0.86602,-0.49999,0.49999,0.86602,-91.50635094610965,158.4936490538903)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(3)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--D-->
          <use
            xlink:href="#icon-3"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(30 415 210)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note4"
          tabindex="0"
          transform="matrix(1,0,0,1,0,0)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(4)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--A-->
          <use
            xlink:href="#icon-4"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(0 415 210)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note5"
          tabindex="0"
          transform="matrix(0.86602,0.5,-0.5,0.86602,158.49364905389052,-91.5063509461097)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(5)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--E-->
          <use
            xlink:href="#icon-5"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(330 415 210)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note6"
          transform="matrix(0.5,0.86602,-0.86602,0.5,341.5063509461096,-91.5063509461097)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(6)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--B-->
          <use
            xlink:href="#icon-6"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(300 415 210)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note7"
          tabindex="0"
          transform="matrix(0,1,-1,0,500.00000000000006,0)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(7)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--F sharp-->
          <use
            xlink:href="#icon-7"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(270 412 207)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note8"
          tabindex="0"
          transform="matrix(-0.5,0.86602,-0.86602,-0.5,591.5063509461097,158.4936490538905)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(8)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--D flat-->
          <use
            xlink:href="#icon-8"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(240 412 207)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note9"
          tabindex="0"
          transform="matrix(-0.86602,0.5,-0.5,-0.86602,591.5063509461097,341.5063509461096)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(9)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--A flat-->
          <use
            xlink:href="#icon-9"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 412 207)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note10"
          tabindex="0"
          transform="matrix(-1,0,0,-1,500,500)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(10)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--E flat-->
          <use
            xlink:href="#icon-10"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(180 412 207)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note11"
          tabindex="0"
          transform="matrix(-0.86602,-0.49999,0.49999,-0.86602,341.5063509461097,591.5063509461097)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(11)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--B flat-->
          <use
            xlink:href="#icon-11"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(150 412 207)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
        <a
          class="item"
          ref="note12"
          tabindex="0"
          transform="matrix(-0.49999,-0.86602,0.86602,-0.49999,158.49364905389024,591.5063509461097)"
          data-svg-origin="250 250"
          style=""
          @click="selectNote(12)"
        >
          <path
            class="sector"
            d="M250,250 l250,0 A250,250 0 0,0 466.5063509461097,125.00000000000001 z"
          ></path>
          <!--F-->
          <use
            xlink:href="#icon-12"
            class="note"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(120 415 210)"
          ></use>
          <use
            xlink:href="#indicator"
            width="40"
            height="40"
            x="394.2073974609375"
            y="186.00076293945312"
            transform="rotate(210 457 182)"
            class="indicator"
          ></use>
        </a>
      </g>
      <g id="trigger" class="trigger menu-trigger" role="button">
        <circle cx="250" cy="250" r="30"></circle>
        <!-- menu button label or icon goes here -->
      </g>
    </svg>
  </div>
</template>

<script>
import { mapActions, mapState } from 'vuex';

import removeClasses from '@/utils/removeClasses';

export default {
  name: 'CircleFifths',
  computed: {
    ...mapState([
      'instrument1',
      'instrument2',
      'originalNote',
      'transposedNote',
    ]),
  },
  data() {
    return {
      notes: [],
    };
  },
  methods: {
    ...mapActions(['updateNotes']),
    selectNote(note) {
      removeClasses('is-selected');

      this.$refs[`note${note}`].classList.add('is-selected');
      this.updateNotes(note);
    },
  },
  updated() {
    removeClasses('is-transposed');
    this.$refs[`note${this.transposedNote.index}`].classList.add(
      'is-transposed',
    );
  },
};
</script>

<style lang="scss" scoped>
.circle-menu {
  margin: spacer(1) auto;
  width: 24em;
  height: 24em;

  svg {
    display: block;
    overflow: visible;
    margin: 0 auto;
  }

  a {
    outline: none;
    cursor: pointer;
  }

  symbol {
    overflow: visible; // KEEP THIS so that text will not get cut off it it is wider than the icon width
  }
}

.note {
  font-size: 2rem;
}

.with-enharmonic {
  font-size: 2rem;

  .flat,
  .sharp {
    font-size: 60%;
  }
}

.enharmonic {
  font-size: 1.75rem;
  fill: $info;
}

.item {
  color: $default;
  -webkit-tap-highlight-color: transparent;

  .note {
    fill: lighten($default, 10%);
  }

  &:hover .sector {
    fill: #eee;
  }

  .sector {
    transition: all 0.1s linear;
    fill: #fff;
    stroke: $info;
  }

  .indicator {
    display: none;
    fill: $primary;
  }
}

.is-selected,
.is-selected.item:hover {
  .sector {
    fill: $secondary;
  }

  .note {
    fill: white;
  }
}

.is-transposed,
.is-transposed:hover {
  .indicator {
    display: block;
  }
}

.menu-trigger {
  pointer-events: auto;
  fill: $info;
}
</style>
